language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm t
  - npm run _build
after_success:
  - npm run _documentation
  - npm run _report
  - npm run _semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
